### ISSUE TITLE
update_field with resolveWith do not mix

### ISSUE THREAD

**Issue by chris-twiner** [sparkutils/quality#38]
low prio as its possibly not needed to be fixed with later spark versions resolving improvements.

swappiing: 

```scala
  @Test // RuleEngineTest: 60
  def testSimpleProductionRules(): Unit = evalCodeGensNoResolve {
```

to evalCodeGens causes:

```scala
java.lang.ClassCastException: org.apache.spark.sql.qualityFunctions.NamedLambdaVariableCodeGen cannot be cast to org.apache.spark.sql.catalyst.expressions.NamedLambdaVariable
	at org.apache.spark.sql.qualityFunctions.FunN.$anonfun$elementVars$1(ReferenceFunctions.scala:232)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.qualityFunctions.FunN.elementVars$lzycompute(ReferenceFunctions.scala:232)
	at org.apache.spark.sql.qualityFunctions.FunN.elementVars(ReferenceFunctions.scala:232)
	at org.apache.spark.sql.qualityFunctions.FunN.eval(ReferenceFunctions.scala:236)
	at org.apache.spark.sql.catalyst.expressions.IsNull.eval(nullExpressions.scala:325)
```

**Comment by chris-twiner** [comment]
affects versions 313 and below, same detected with #81
