### ISSUE TITLE
13.3 DBR target needed

### ISSUE THREAD

**Issue by chris-twiner** [sparkutils/quality#59]
java.lang.NoSuchMethodError: org.apache.spark.sql.types.AtomicType.ordering()Lscala/math/Ordering;
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.Analyzer.ResolveUserSpecifiedColumns()Lorg/apache/spark/sql/catalyst/analysis/Analyzer$ResolveUserSpecifiedColumns$;

on 13.1 build (shim based).

**Comment by chris-twiner** [comment]
````
4) testSimpleProductionRulesReplaceDebug(com.sparkutils.qualityTests.RuleFolderTest)
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.ScalaReflection$.isNativeType(Lorg/apache/spark/sql/types/DataType;)Z
	at org.apache.spark.sql.reflection.package$.isNativeType(package.scala:16)
	at frameless.TypedEncoder$$anon$17.toCatalyst(TypedEncoder.scala:343)
	at frameless.TypedEncoder$$anon$19.toCatalyst(TypedEncoder.scala:505)
	at frameless.RecordEncoder.$anonfun$toCatalyst$2(RecordEncoder.scala:155)
	at scala.collection.immutable.List.map(List.scala:297)
	at frameless.RecordEncoder.toCatalyst(RecordEncoder.scala:153)
	at frameless.TypedExpressionEncoder$.apply(TypedExpressionEncoder.scala:28)
	at com.sparkutils.quality.impl.EncodersImplicits.ruleFolderResultExpEnc(SparkHelpers.scala:107)
	at com.sparkutils.quality.impl.EncodersImplicits.ruleFolderResultExpEnc$(SparkHelpers.scala:107)
	at com.sparkutils.quality.implicits.package$.ruleFolderResultExpEnc(package.scala:8)
	at com.sparkutils.qualityTests.RuleFolderTest.$anonfun$doTestSimpleProductionRulesReplaceDebug$1(RuleFolderTest.scala:226)
````

won't run without frameless being shimmed, they've backported that as well.
